name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mysql-install
      run: sudo apt-get update&&sudo apt-get install -y mysql-server mysql-common mysql-client
    - name: perms
      run: chmod +x ./configure
    - name: configure
      run: ./configure --with-mysql --with-mysql-lib=/usr/lib/x86_64-linux-gnu/ --with-zlib=/usr/lib/x86_64-linux-gnu/
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
